apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: nginxjs
    color: blue
spec:
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: nginxjs
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: nginxjs
        color: blue
    spec:
      containers:
      - image: docker.io/takumiseo/handson-ci-image:f37276c2618b6bb60b78c47143cf34ae386fa8d1
        name: blue
        ports:
          - containerPort: 80
