apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: nginxjs
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: nginxjs
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: nginxjs
        color: blue
    spec:
      containers:
      - image: docker.io/takuyak/demo-aks-gitops:f267143a4c9e2122c5a378a7ec11b4d15f9a95d9
        name: blue
        ports:
          - containerPort: 80
